
//----------------------------------------------------
// The following code was generated by CUP v0.11b ${cupversion} (SVN rev )
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 27;
  public static final int DIVIDE = 32;
  public static final int EQUALS = 36;
  public static final int UMINUS = 42;
  public static final int GREATER = 39;
  public static final int LPAREN = 19;
  public static final int INT = 3;
  public static final int LESS = 38;
  public static final int MINUS = 30;
  public static final int WRITE = 24;
  public static final int SCAN = 8;
  public static final int RPAREN = 20;
  public static final int NOT = 33;
  public static final int SEMICOLON = 21;
  public static final int AND = 34;
  public static final int RECORD = 7;
  public static final int OR = 35;
  public static final int BOOL = 2;
  public static final int COMMA = 22;
  public static final int PLUS = 29;
  public static final int LESSEQ = 40;
  public static final int ASSIGN = 26;
  public static final int IF = 10;
  public static final int DOT = 23;
  public static final int ID = 14;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 28;
  public static final int RETURN = 13;
  public static final int TRUE = 5;
  public static final int error = 1;
  public static final int LCURLY = 17;
  public static final int VOID = 4;
  public static final int RCURLY = 18;
  public static final int INTLITERAL = 15;
  public static final int TIMES = 31;
  public static final int ELSE = 11;
  public static final int READ = 25;
  public static final int NOTEQUALS = 37;
  public static final int WHILE = 12;
  public static final int GREATEREQ = 41;
  public static final int STRINGLITERAL = 16;
  public static final int FALSE = 6;
  public static final int PRINT = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL",
  "INT",
  "VOID",
  "TRUE",
  "FALSE",
  "RECORD",
  "SCAN",
  "PRINT",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "ID",
  "INTLITERAL",
  "STRINGLITERAL",
  "LCURLY",
  "RCURLY",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "WRITE",
  "READ",
  "ASSIGN",
  "PLUSPLUS",
  "MINUSMINUS",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "NOT",
  "AND",
  "OR",
  "EQUALS",
  "NOTEQUALS",
  "LESS",
  "GREATER",
  "LESSEQ",
  "GREATEREQ",
  "UMINUS"
  };
}

